// actionTypes.js
export const FETCH_OTHERSTATS = 'FETCH_OTHERSTATS';
export const FETCH_OTHERSTATS_FAIL = 'FETCH_OTHERSTATS_FAIL';

export const FETCH_ADMIN_NOTIFS = 'FETCH_ADMIN_NOTIFS';
export const FETCH_ADMIN_NOTIFS_FAIL = 'FETCH_ADMIN_NOTIFS_FAIL';

export const FETCH_AUTHUSER = 'FETCH_AUTHUSER';
export const FETCH_AUTHUSER_FAIL = 'FETCH_AUTHUSER_FAIL';